import{a as v,S as P,i as s}from"./assets/vendor-Db2TdIkw.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const B="https://pixabay.com/api/",O="49684805-156d2cdb1a1bccc9916216ec8",R=15;async function p(o,r=1){return(await v.get(B,{params:{key:O,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:R}})).data}const f=document.querySelector(".gallery"),h=document.querySelector(".loader"),g=document.querySelector(".load-more");let $=new P(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const r=o.map(({webformatURL:a,largeImageURL:c,tags:e,likes:t,views:i,comments:b,downloads:q})=>`
      <li class="gallery-item">
        <a href="${c}">
          <img src="${a}" alt="${e}" />
        </a>
        <div class="image-info">
          <p>Likes: ${t}</p>
          <p>Views: ${i}</p>
          <p>Comments: ${b}</p>
          <p>Downloads: ${q}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",r),$.refresh()}function E(){f.innerHTML=""}function L(){h.classList.remove("hidden")}function w(){h.classList.add("hidden")}function S(){g.classList.remove("hidden")}function u(){g.classList.add("hidden")}const M=document.querySelector(".form");document.querySelector(".gallery");const x=document.querySelector(".load-more");document.querySelector(".loader");let l="",n=1;const d=15;let m=0;M.addEventListener("submit",async o=>{if(o.preventDefault(),l=o.target.elements["search-text"].value.trim(),!l){s.warning({message:"Please enter a search term!",position:"topRight"});return}n=1,E(),u(),L();try{const r=await p(l,n,d);if(m=r.totalHits,r.hits.length===0){s.info({message:"Sorry, there are no images matching your search query.",position:"topRight"});return}y(r.hits),d*n<m&&S()}catch{s.error({message:"Oops! Something went wrong.",position:"topRight"})}finally{w()}});x.addEventListener("click",async()=>{n+=1,L(),u();try{const o=await p(l,n,d);y(o.hits),d*n>=m?(u(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):S(),A()}catch{s.error({message:"Oops! Something went wrong.",position:"topRight"})}finally{w()}});function A(){const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
